export const NL_PO = {
  id: 'NL_PO',
  titleKey: 'curriculum.nl_po.title',
  countryCode: 'NL',
  countryKey: 'curriculum.country.nl',
  fallbackStagePrefixKey: 'curriculum.stage',
  stages: [
    { id: 'grade_1', order: 1, minAge: 4, maxAge: 5, labelKey: 'curriculum.nl_po.stage.grade_1' },
    { id: 'grade_2', order: 2, minAge: 5, maxAge: 6, labelKey: 'curriculum.nl_po.stage.grade_2' },
    { id: 'grade_3', order: 3, minAge: 6, maxAge: 7, labelKey: 'curriculum.nl_po.stage.grade_3' },
    { id: 'grade_4', order: 4, minAge: 7, maxAge: 8, labelKey: 'curriculum.nl_po.stage.grade_4' },
    { id: 'grade_5', order: 5, minAge: 8, maxAge: 9, labelKey: 'curriculum.nl_po.stage.grade_5' },
    { id: 'grade_6', order: 6, minAge: 9, maxAge: 10, labelKey: 'curriculum.nl_po.stage.grade_6' },
    { id: 'grade_7', order: 7, minAge: 10, maxAge: 11, labelKey: 'curriculum.nl_po.stage.grade_7' },
    { id: 'grade_8', order: 8, minAge: 11, maxAge: 12, labelKey: 'curriculum.nl_po.stage.grade_8' },
  ],
  domains: [
    { id: 'numbers', labelKey: 'curriculum.domain.numbers' },
    { id: 'operations', labelKey: 'curriculum.domain.operations' },
    { id: 'ratios', labelKey: 'curriculum.domain.ratios' },
    { id: 'measurement_geometry', labelKey: 'curriculum.domain.measurement_geometry' },
    { id: 'data_relationships', labelKey: 'curriculum.domain.data_relationships' },
  ],
  objectives: [
    { id: 'nl_po.grade3.add_sub_to_20', stage: 'grade_3', domain: 'operations', titleKey: 'curriculum.nl_po.objective.add_sub_to_20', status: 'playable', gameSkills: ['add_20', 'sub_20'] },
    { id: 'nl_po.grade3.missing_addend_intro', stage: 'grade_3', domain: 'operations', titleKey: 'curriculum.nl_po.objective.missing_addend_intro', status: 'playable', gameSkills: ['missing_addend'] },
    { id: 'nl_po.grade4.add_sub_to_100', stage: 'grade_4', domain: 'operations', titleKey: 'curriculum.nl_po.objective.add_sub_to_100', status: 'playable', gameSkills: ['add_100', 'sub_100'] },
    { id: 'nl_po.grade4.tables_2_5_10', stage: 'grade_4', domain: 'operations', titleKey: 'curriculum.nl_po.objective.tables_2_5_10', status: 'playable', gameSkills: ['tables_a'], businessModes: ['repeated_addition_orders'] },
    { id: 'nl_po.grade4.fair_sharing_intro', stage: 'grade_4', domain: 'operations', titleKey: 'curriculum.nl_po.objective.fair_sharing_intro', status: 'playable', gameSkills: ['share'], businessModes: ['portion_halves_quarters'] },
    { id: 'nl_po.grade4.money_to_100', stage: 'grade_4', domain: 'measurement_geometry', titleKey: 'curriculum.nl_po.objective.money_to_100', status: 'playable', gameSkills: [], businessModes: ['money_make_amounts'] },
    { id: 'nl_po.grade5.tables_3_4_6', stage: 'grade_5', domain: 'operations', titleKey: 'curriculum.nl_po.objective.tables_3_4_6', status: 'playable', gameSkills: ['tables_b'] },
    { id: 'nl_po.grade5.tables_7_8_9', stage: 'grade_5', domain: 'operations', titleKey: 'curriculum.nl_po.objective.tables_7_8_9', status: 'playable', gameSkills: ['tables_c'] },
    { id: 'nl_po.grade5.all_tables_mixed', stage: 'grade_5', domain: 'operations', titleKey: 'curriculum.nl_po.objective.all_tables_mixed', status: 'playable', gameSkills: ['tables_mix'] },
    { id: 'nl_po.grade5.measurement_units_intro', stage: 'grade_5', domain: 'measurement_geometry', titleKey: 'curriculum.nl_po.objective.measurement_units_intro', status: 'playable', gameSkills: [], businessModes: ['recipe_measure_whole'] },
    { id: 'nl_po.grade5.decimal_money_context', stage: 'grade_5', domain: 'measurement_geometry', titleKey: 'curriculum.nl_po.objective.decimal_money_context', status: 'playable', gameSkills: [], businessModes: ['decimal_money_change'] },
    { id: 'nl_po.grade6.multi_digit_multiplication', stage: 'grade_6', domain: 'operations', titleKey: 'curriculum.nl_po.objective.multi_digit_multiplication', status: 'playable', gameSkills: ['mult_2digit'] },
    { id: 'nl_po.grade6.division_facts_and_inverse', stage: 'grade_6', domain: 'operations', titleKey: 'curriculum.nl_po.objective.division_facts_and_inverse', status: 'playable', gameSkills: ['div_facts', 'missing_factor'] },
    { id: 'nl_po.grade6.division_with_remainders', stage: 'grade_6', domain: 'operations', titleKey: 'curriculum.nl_po.objective.division_with_remainders', status: 'playable', gameSkills: ['div_remainder'] },
    { id: 'nl_po.grade6.fraction_magnitude', stage: 'grade_6', domain: 'ratios', titleKey: 'curriculum.nl_po.objective.fraction_magnitude', status: 'playable', gameSkills: ['frac_magnitude'] },
    { id: 'nl_po.grade6.fraction_of_quantity', stage: 'grade_6', domain: 'ratios', titleKey: 'curriculum.nl_po.objective.fraction_of_quantity', status: 'playable', gameSkills: ['frac_of_n'], businessModes: ['fraction_of_quantity_recipe'] },
    { id: 'nl_po.grade6.unit_conversion_context', stage: 'grade_6', domain: 'measurement_geometry', titleKey: 'curriculum.nl_po.objective.unit_conversion_context', status: 'playable', gameSkills: [], businessModes: ['unit_conversion_stock'] },
    { id: 'nl_po.grade6.price_comparison', stage: 'grade_6', domain: 'data_relationships', titleKey: 'curriculum.nl_po.objective.price_comparison', status: 'playable', gameSkills: [], businessModes: ['price_compare'] },
    { id: 'nl_po.grade7.fraction_compare_equivalence', stage: 'grade_7', domain: 'ratios', titleKey: 'curriculum.nl_po.objective.fraction_compare_equivalence', status: 'playable', gameSkills: ['frac_compare', 'frac_equiv'] },
    { id: 'nl_po.grade7.percentages_intro', stage: 'grade_7', domain: 'ratios', titleKey: 'curriculum.nl_po.objective.percentages_intro', status: 'playable', gameSkills: [], businessModes: ['percentage_discount'] },
    { id: 'nl_po.grade7.profit_margin_intro', stage: 'grade_7', domain: 'data_relationships', titleKey: 'curriculum.nl_po.objective.profit_margin_intro', status: 'playable', gameSkills: [], businessModes: ['profit_margin'] },
    { id: 'nl_po.grade7.scale_recipe', stage: 'grade_7', domain: 'measurement_geometry', titleKey: 'curriculum.nl_po.objective.scale_recipe', status: 'playable', gameSkills: [], businessModes: ['scale_recipe'] },
    { id: 'nl_po.grade7.scale_and_coordinates', stage: 'grade_7', domain: 'measurement_geometry', titleKey: 'curriculum.nl_po.objective.scale_and_coordinates', status: 'planned', gameSkills: [] },
    { id: 'nl_po.grade8.operations_maintenance', stage: 'grade_8', domain: 'operations', titleKey: 'curriculum.nl_po.objective.operations_maintenance', status: 'playable', gameSkills: ['mult_2digit', 'div_remainder'] },
    { id: 'nl_po.grade8.fraction_decimal_percent_relations', stage: 'grade_8', domain: 'ratios', titleKey: 'curriculum.nl_po.objective.fraction_decimal_percent_relations', status: 'playable', gameSkills: ['frac_compare', 'frac_equiv', 'frac_of_n'] },
    { id: 'nl_po.grade8.inverse_reasoning', stage: 'grade_8', domain: 'operations', titleKey: 'curriculum.nl_po.objective.inverse_reasoning', status: 'playable', gameSkills: ['missing_factor'] },
    { id: 'nl_po.grade8.advanced_data_reasoning', stage: 'grade_8', domain: 'data_relationships', titleKey: 'curriculum.nl_po.objective.advanced_data_reasoning', status: 'playable', gameSkills: [], businessModes: ['demand_chart'] },
  ],
};
