import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

// https://vite.dev/config/
export default defineConfig({
  // served from https://<user>.github.io/monkeygrove/ via `npm run deploy`
  base: '/monkeygrove/',
  plugins: [
    // Offline-capable PWA so the game loads + plays on flaky school Wi-Fi and can be
    // installed to the home screen. autoUpdate avoids cache-trapping users on a stale
    // build. Icons live in public/ (generated by scripts/gen-icons.mjs).
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['apple-touch-icon.png'],
      manifest: {
        name: 'Monkey Grove',
        short_name: 'Monkey Grove',
        description: 'A cozy island adventure that secretly teaches arithmetic.',
        theme_color: '#7ccf7c',
        background_color: '#bfe8f7',
        display: 'standalone',
        orientation: 'any',
        icons: [
          { src: 'pwa-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'pwa-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // Precache the app shell. The OpenDyslexic woff2 (235 KB) is deliberately excluded —
        // it's an opt-in font most kids never enable, lazy-loaded by src/a11y.js. The three.js
        // chunk is large, so lift the cap.
        globPatterns: ['**/*.{js,css,html,png,svg}'],
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
        // Runtime-cache the dyslexia font on first use so it still works offline once enabled.
        runtimeCaching: [
          {
            urlPattern: /\.woff2$/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'dyslexia-fonts',
              expiration: { maxEntries: 4, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
    }),
  ],
  server: {
    port: 5173,
    open: true,
  },
  build: {
    outDir: 'dist',
    target: 'es2022',
    chunkSizeWarningLimit: 1200, // three.js in one vendor chunk is fine
  },
  test: {
    environment: 'node',
    include: ['tests/**/*.test.mjs'],
    fileParallelism: false,
  },
});
