import { defineConfig } from 'vite';
import { VitePWA } from 'vite-plugin-pwa';

// https://vite.dev/config/
export default defineConfig({
  // served from https://<user>.github.io/monkeygrove/ via `npm run deploy`
  base: '/monkeygrove/',
  plugins: [
    // Offline-capable PWA so the game loads + plays on flaky school Wi-Fi and can be
    // installed to the home screen. autoUpdate avoids cache-trapping users on a stale
    // build. Icons live in public/ (generated by scripts/gen-icons.mjs).
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['apple-touch-icon.png'],
      manifest: {
        name: 'Monkey Grove',
        short_name: 'Monkey Grove',
        description: 'A cozy island adventure that secretly teaches arithmetic.',
        theme_color: '#7ccf7c',
        background_color: '#bfe8f7',
        display: 'standalone',
        orientation: 'any',
        icons: [
          { src: 'pwa-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'pwa-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'pwa-maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      workbox: {
        // precache the app shell incl. fonts; the three.js chunk is large, so lift the cap
        globPatterns: ['**/*.{js,css,html,woff2,png,svg}'],
        maximumFileSizeToCacheInBytes: 3 * 1024 * 1024,
      },
    }),
  ],
  server: {
    port: 5173,
    open: true,
  },
  build: {
    outDir: 'dist',
    target: 'es2022',
    chunkSizeWarningLimit: 1200, // three.js in one vendor chunk is fine
  },
  test: {
    environment: 'node',
    include: ['tests/**/*.test.mjs'],
    fileParallelism: false,
  },
});
