// The Crab King: bigger, grander, crowned. Comically apologetic later on.
export const crabKing = {
  palette: {
    R: '#e87a6a',
    r: '#ffb3a0',
    d: '#c95f51',
    G: '#f4c95d',
    E: '#2e2433',
    W: '#ffffff',
  },
  layers: [
    [ // y0 legs
      '.............',
      '.............',
      '.d.........d.',
      '.............',
      '.d.........d.',
    ],
    [ // y1 body + claw arms
      '.............',
      '..RRRRRRRRR..',
      '.RRRRRRRRRRR.',
      '.RRRRRRRRRRR.',
      '.RRRRRRRRRRR.',
      'r.rrrrrrrrr.r',
      'rr.........rr',
    ],
    [ // y2 body + claw arms
      '.............',
      '..RRRRRRRRR..',
      '.RRRRRRRRRRR.',
      '.RRRRRRRRRRR.',
      '.RRRRRRRRRRR.',
      'r.rrrrrrrrr.r',
      'rr.........rr',
    ],
    [ // y3 body, pincers opening
      '.............',
      '..RRRRRRRRR..',
      '.RRRRRRRRRRR.',
      '.RRRRRRRRRRR.',
      '.RRRRRRRRRRR.',
      'r.rrrrrrrrr.r',
      'r...........r',
    ],
    [ // y4 dome + pincer tips
      '.............',
      '.............',
      '..RRRRRRRRR..',
      '.RRRRRRRRRRR.',
      '..RRRRRRRRR..',
      'r...........r',
    ],
    [ // y5 dome
      '.............',
      '.............',
      '...RRRRRRR...',
      '..RRRRRRRRR..',
      '...RRRRRRR...',
    ],
    [ // y6 dome top
      '.............',
      '.............',
      '.............',
      '....RRRRR....',
      '....rrrrr....',
    ],
    [ // y7 crown base + eye stalks
      '.............',
      '.............',
      '.............',
      '....GGGGG....',
      '....d...d....',
    ],
    [ // y8 crown points + stalks
      '.............',
      '.............',
      '.............',
      '....G.G.G....',
      '....d...d....',
    ],
    [ // y9 crown peak + stalks
      '.............',
      '.............',
      '.............',
      '......G......',
      '....d...d....',
    ],
    [ // y10 eyes
      '.............',
      '.............',
      '.............',
      '.............',
      '...EE...EE...',
    ],
    [ // y11 eye tops with glints
      '.............',
      '.............',
      '.............',
      '.............',
      '...WE...WE...',
    ],
  ],
};
